version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        patterns:
          - "*" # All updates are grouped in 1 PR

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "monthly"
    # Create a group of dependencies to be updated together in one pull request
    groups:
      dev-dependencies:
        patterns:
          - "*" # All updates are grouped in 1 PR
