name: Publish docs
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: '/home/runner/.cache/bazel'
          key: bazel
          save-always: true
      - name: Generate docs
        run: bazel run //website:docusaurus-build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        # If you're changing the branch from master,
        # also change the `master` in `refs/heads/master`
        # below accordingly.
        if: github.ref == 'refs/heads/master'
        with:
          personal_token: ${{ secrets.WEBSITE_PUBLISH_TOKEN }}
          publish_dir: ./bazel-bin/website/docusaurus-build_/docusaurus-build.runfiles/_main/website/build
          external_repository: build-server-protocol/build-server-protocol.github.io
          publish_branch: master
